apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: installationtargets.shipper.booking.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: shipper.booking.com
  # version name to use for REST API: /apis/<group>/<version>
  versions:
  - name: v1alpha1
    served: true
    storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: installationtargets
    # singular name to be used as an alias on the CLI and for display
    singular: installationtarget
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: InstallationTarget
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - it
    categories:
    - shipper
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - clusters
          - canOverride
          properties:
            clusters:
              type: array
              items:
                type: string
            canOverride:
              type: boolean
            chart:
              type: object
              required:
              - name
              - version
              - repoUrl
              properties:
                name:
                  type: string
                version:
                  type: string
                repoUrl:
                  type: string
            values:
              type: object
