apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: releases.shipper.booking.com
spec:
  # additional columns to print for kubectl get command besides NAME and AGE
  # and NAMESPACE (in case of passing --all-namespaces flag)
  additionalPrinterColumns:
  - JSONPath: .status.achievedStep.name
    description: The current achieved step for a release as defined in the rollout strategy.
    name: Step
    type: string
  - JSONPath: .status.conditions[?(@.status=="False")].reason
    description: Errors from False conditions that show what's wrong with the release.
    name: Errors
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: The release's age.
    name: Age
    type: date
  - JSONPath: .metadata.annotations.shipper\.booking\.com\/release\.clusters
    description: The list of clusters where a release is supposed to be rolled out as per strategy.
    name: Clusters
    type: string
    priority: -1
  # group name to use for REST API: /apis/<group>/<version>
  group: shipper.booking.com
  # version name to use for REST API: /apis/<group>/<version>
  versions:
  - name: v1alpha1
    served: true
    storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: releases
    # singular name to be used as an alias on the CLI and for display
    singular: release
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Release
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - rel
    categories:
    - all
    - shipper
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - environment
          - targetStep
          properties:
            targetStep:
              type: integer
              minimum: 0
            environment:
              type: object
              required:
              - chart
              - strategy
              - values
              - clusterRequirements
              properties:
                chart:
                  type: object
                  required:
                  - name
                  - version
                  - repoUrl
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                    repoUrl:
                      type: string
                clusterRequirements:
                  type: object
                  required:
                  - regions
                  properties:
                    regions:
                      type: array
                      items:
                        type: object
                    capabilities:
                      type: array
                      items:
                        type: string
                strategy:
                  type: object
                  required:
                  - steps
                  properties:
                    steps:
                      type: array
                      items:
                        type: object
                        required:
                        - name
                        - traffic
                        - capacity
                        properties:
                          name:
                            type: string
                          capacity:
                            type: object
                            required:
                            - incumbent
                            - contender
                            properties:
                              incumbent:
                                type: integer
                                minimum: 0
                                maximum: 100
                              contender:
                                type: integer
                                minimum: 0
                                maximum: 100
                          traffic:
                            type: object
                            required:
                            - incumbent
                            - contender
                            properties:
                              incumbent:
                                type: integer
                                minimum: 0
                                maximum: 100
                              contender:
                                type: integer
                                minimum: 0
                                maximum: 100
                values:
                  type: object
