apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: releases.stable.shipper
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.shipper
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: releases
    # singular name to be used as an alias on the CLI and for display
    singular: release
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Release
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - rel
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - targetStep
          properties:
            targetStep:
              type: integer
              minimum: 0
        environment:
          type: object
          required:
          - chart
          - shipmentOrder
          - sidecars
          properties:
            chart:
              type: object
              required:
              - name
              - version
              - tarball
              properties:
                name:
                  type: string
                version:
                  type: string
                tarball:
                  type: string # base64?
            sidecars:
              type: array
              items:
                type: object
                required:
                - name
                - version
                properties:
                  name:
                    type: string
                  version:
                    type: string
            shipmentOrder:
              type: object
              required:
              - clusterSelectors
              - strategy
              - values
              properties:
                clusterSelectors:
                  type: array
                  items:
                    type: object
                    properties:
                      regions:
                        type: array
                        items:
                          type: string
                      capabilities:
                        type: array
                        items:
                          type: string
                strategy:
                  type: string
                values:
                  type: object
