apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: rolloutblocks.shipper.booking.com
spec:
  # additional columns to print for kubectl get command besides NAME and AGE
  # and NAMESPACE (in case of passing --all-namespaces flag)
  additionalPrinterColumns:
  - JSONPath: .spec.message
    description: The reason for this rollout block.
    name: Message
    type: string
  - JSONPath: .spec.author.type
    priority: 1
    description: The author type of this Rollout Block object.
    name: Author Type
    type: string
  - JSONPath: .spec.author.name
    priority: 1
    description: The author name of this Rollout Block object.
    name: Author Name
    type: string
  - JSONPath: .status.overrides.application
    priority: 1
    description: The list of applications that overrides this rollout block.
    name: Overriding Applications
    type: string
  - JSONPath: .status.overrides.release
    priority: 1
    description: The list of releases that overrides this rollout block.
    name: Overriding Releases
    type: string
  # group name to use for REST API: /apis/<group>/<version>
  group: shipper.booking.com
  # version name to use for REST API: /apis/<group>/<version>
  versions:
    - name: v1alpha1
      served: true
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: rolloutblocks
    # singular name to be used as an alias on the CLI and for display
    singular: rolloutblock
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: RolloutBlock
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - rb
    categories:
    - all
    - shipper
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - message
            - author
          properties:
            message:
              type: string
            author:
              type: object
              required:
              - type
              - name
              properties:
                type:
                  type: string
                name:
                  type: string