apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: traffictargets.shipper.booking.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: shipper.booking.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: traffictargets
    # singular name to be used as an alias on the CLI and for display
    singular: traffictarget
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TrafficTarget
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - clusters
          properties:
            clusters:
              type: array
              items:
                type: object
                required:
                - name
                - weight
                properties:
                  name:
                    type: string
                  weight:
                    minimum: 0
                    type: integer
