/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/bookingcom/shipper/pkg/apis/shipper/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ApplicationClusterLister helps list ApplicationClusters.
type ApplicationClusterLister interface {
	// List lists all ApplicationClusters in the indexer.
	List(selector labels.Selector) (ret []*v1.ApplicationCluster, err error)
	// Get retrieves the ApplicationCluster from the index for a given name.
	Get(name string) (*v1.ApplicationCluster, error)
	ApplicationClusterListerExpansion
}

// applicationClusterLister implements the ApplicationClusterLister interface.
type applicationClusterLister struct {
	indexer cache.Indexer
}

// NewApplicationClusterLister returns a new ApplicationClusterLister.
func NewApplicationClusterLister(indexer cache.Indexer) ApplicationClusterLister {
	return &applicationClusterLister{indexer: indexer}
}

// List lists all ApplicationClusters in the indexer.
func (s *applicationClusterLister) List(selector labels.Selector) (ret []*v1.ApplicationCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ApplicationCluster))
	})
	return ret, err
}

// Get retrieves the ApplicationCluster from the index for a given name.
func (s *applicationClusterLister) Get(name string) (*v1.ApplicationCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("applicationcluster"), name)
	}
	return obj.(*v1.ApplicationCluster), nil
}
