/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

// ApplicationListerExpansion allows custom methods to be added to
// ApplicationLister.
type ApplicationListerExpansion interface{}

// ApplicationNamespaceListerExpansion allows custom methods to be added to
// ApplicationNamespaceLister.
type ApplicationNamespaceListerExpansion interface{}

// CapacityTargetListerExpansion allows custom methods to be added to
// CapacityTargetLister.
type CapacityTargetListerExpansion interface{}

// CapacityTargetNamespaceListerExpansion allows custom methods to be added to
// CapacityTargetNamespaceLister.
type CapacityTargetNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// InstallationTargetListerExpansion allows custom methods to be added to
// InstallationTargetLister.
type InstallationTargetListerExpansion interface{}

// InstallationTargetNamespaceListerExpansion allows custom methods to be added to
// InstallationTargetNamespaceLister.
type InstallationTargetNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}

// StrategyListerExpansion allows custom methods to be added to
// StrategyLister.
type StrategyListerExpansion interface{}

// StrategyNamespaceListerExpansion allows custom methods to be added to
// StrategyNamespaceLister.
type StrategyNamespaceListerExpansion interface{}

// TrafficTargetListerExpansion allows custom methods to be added to
// TrafficTargetLister.
type TrafficTargetListerExpansion interface{}

// TrafficTargetNamespaceListerExpansion allows custom methods to be added to
// TrafficTargetNamespaceLister.
type TrafficTargetNamespaceListerExpansion interface{}
