/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/bookingcom/shipper/pkg/apis/shipper/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ShipmentOrderLister helps list ShipmentOrders.
type ShipmentOrderLister interface {
	// List lists all ShipmentOrders in the indexer.
	List(selector labels.Selector) (ret []*v1.ShipmentOrder, err error)
	// ShipmentOrders returns an object that can list and get ShipmentOrders.
	ShipmentOrders(namespace string) ShipmentOrderNamespaceLister
	ShipmentOrderListerExpansion
}

// shipmentOrderLister implements the ShipmentOrderLister interface.
type shipmentOrderLister struct {
	indexer cache.Indexer
}

// NewShipmentOrderLister returns a new ShipmentOrderLister.
func NewShipmentOrderLister(indexer cache.Indexer) ShipmentOrderLister {
	return &shipmentOrderLister{indexer: indexer}
}

// List lists all ShipmentOrders in the indexer.
func (s *shipmentOrderLister) List(selector labels.Selector) (ret []*v1.ShipmentOrder, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ShipmentOrder))
	})
	return ret, err
}

// ShipmentOrders returns an object that can list and get ShipmentOrders.
func (s *shipmentOrderLister) ShipmentOrders(namespace string) ShipmentOrderNamespaceLister {
	return shipmentOrderNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ShipmentOrderNamespaceLister helps list and get ShipmentOrders.
type ShipmentOrderNamespaceLister interface {
	// List lists all ShipmentOrders in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.ShipmentOrder, err error)
	// Get retrieves the ShipmentOrder from the indexer for a given namespace and name.
	Get(name string) (*v1.ShipmentOrder, error)
	ShipmentOrderNamespaceListerExpansion
}

// shipmentOrderNamespaceLister implements the ShipmentOrderNamespaceLister
// interface.
type shipmentOrderNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ShipmentOrders in the indexer for a given namespace.
func (s shipmentOrderNamespaceLister) List(selector labels.Selector) (ret []*v1.ShipmentOrder, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ShipmentOrder))
	})
	return ret, err
}

// Get retrieves the ShipmentOrder from the indexer for a given namespace and name.
func (s shipmentOrderNamespaceLister) Get(name string) (*v1.ShipmentOrder, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("shipmentorder"), name)
	}
	return obj.(*v1.ShipmentOrder), nil
}
