/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/bookingcom/shipper/pkg/apis/shipper/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TargetClusterLister helps list TargetClusters.
type TargetClusterLister interface {
	// List lists all TargetClusters in the indexer.
	List(selector labels.Selector) (ret []*v1.TargetCluster, err error)
	// Get retrieves the TargetCluster from the index for a given name.
	Get(name string) (*v1.TargetCluster, error)
	TargetClusterListerExpansion
}

// targetClusterLister implements the TargetClusterLister interface.
type targetClusterLister struct {
	indexer cache.Indexer
}

// NewTargetClusterLister returns a new TargetClusterLister.
func NewTargetClusterLister(indexer cache.Indexer) TargetClusterLister {
	return &targetClusterLister{indexer: indexer}
}

// List lists all TargetClusters in the indexer.
func (s *targetClusterLister) List(selector labels.Selector) (ret []*v1.TargetCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.TargetCluster))
	})
	return ret, err
}

// Get retrieves the TargetCluster from the index for a given name.
func (s *targetClusterLister) Get(name string) (*v1.TargetCluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("targetcluster"), name)
	}
	return obj.(*v1.TargetCluster), nil
}
