FROM alpine:3.8
LABEL authors="Parham Doustdar <parham.doustdar@booking.com>, Alexey Surikov <alexey.surikov@booking.com>, Igor Sutton <igor.sutton@booking.com>, Ben Tyler <benjamin.tyler@booking.com>"
RUN apk add ca-certificates
ADD build/shipper-state-metrics /bin/shipper-state-metrics
ENTRYPOINT ["shipper-state-metrics", "-v", "2"]
