FROM alpine:3.8
LABEL authors="Parham Doustdar <parham.doustdar@booking.com>, Alexey Surikov <alexey.surikov@booking.com>, Igor Sutton <igor.sutton@booking.com>, Ben Tyler <benjamin.tyler@booking.com>"
RUN apk add ca-certificates
ADD build/shipper-mgmt.linux-amd64 /bin/shipper-mgmt
ENTRYPOINT ["shipper-mgmt"]
