apiVersion: shipper.booking.com/v1alpha1
kind: Release
metadata:
  name: super-server-8bdca4a1-0
spec:
  targetStep: 2
  environment:
    chart:
      name: nginx
      version: 0.0.1
      repoUrl: https://raw.githubusercontent.com/bookingcom/shipper/master/test/e2e/testdata
    clusterRequirements:
      capabilities:
        - gpu
        - high-memory-nodes
      regions:
        - name: us-east1
    strategy:
      steps:
        - name: staging
          capacity:
            incumbent: 100
            contender: 1
          traffic:
            incumbent: 100
            contender: 0
        - name: canary
          capacity:
            incumbent: 10
            contender: 90
          traffic:
            incumbent: 10
            contender: 90
        - name: full on
          capacity:
            incumbent: 0
            contender: 100
          traffic:
            incumbent: 0
            contender: 100
    values:
      replicaCount: 2
status:
  achievedStep:
    name: full on
    step: 2
  conditions:
    - lastTransitionTime: "2020-07-13T09:56:57Z"
      status: "False"
      type: Blocked
    - lastTransitionTime: "2020-07-13T09:56:57Z"
      message: kind-app
      reason: ClustersChosen
      status: "True"
      type: ClustersChosen
    - lastTransitionTime: "2020-07-13T09:58:02Z"
      status: "True"
      type: Complete
    - lastTransitionTime: "2020-07-13T09:56:57Z"
      status: "True"
      type: StrategyExecuted
  strategy:
    clusters:
      - name: kind-app
        conditions:
          - lastTransitionTime: "2020-07-13T09:58:02Z"
            message: ""
            reason: ""
            status: "True"
            step: 2
            type: ContenderAchievedCapacity
          - lastTransitionTime: "2020-07-13T09:58:02Z"
            message: ""
            reason: ""
            status: "True"
            step: 2
            type: ContenderAchievedInstallation
          - lastTransitionTime: "2020-07-13T09:58:02Z"
            message: ""
            reason: ""
            status: "True"
            step: 2
            type: ContenderAchievedTraffic
    state:
      waitingForCapacity: "False"
      waitingForCommand: "False"
      waitingForInstallation: "False"
      waitingForTraffic: "False"
