package errors

import (
	"fmt"
	shipper "github.com/bookingcom/shipper/pkg/apis/shipper/v1alpha1"
	"github.com/golang/glog"
	corev1 "k8s.io/api/core/v1"
	kerrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type KubeclientVerb string

const (
	KubeclientVerbCreate   KubeclientVerb = "CREATE"
	KubeclientVerbGet      KubeclientVerb = "GET"
	KubeclientVerbUpdate   KubeclientVerb = "UPDATE"
	KubeclientVerbDelete   KubeclientVerb = "DELETE"
	KubeclientVerbPatch    KubeclientVerb = "PATCH"
	KubeclientVerbList     KubeclientVerb = "LIST"
	KubeclientVerbDiscover KubeclientVerb = "DISCOVER"
)

type KubeclientError struct {
	verb KubeclientVerb
	gvk  schema.GroupVersionKind
	ns   string
	name string
	err  error
}

func (e KubeclientError) Error() string {
	var fqn string
	if e.ns == "" {
		fqn = e.name
	} else {
		fqn = fmt.Sprintf("%s/%s", e.ns, e.name)
	}

	return fmt.Sprintf("failed to %s %s %q: %s", e.verb, e.gvk.Kind, fqn, e.err)
}

// ShouldRetry determines if the error generated by an API call will be
// retried. It follows API conventions stipulated by
// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#http-status-codes
func (e KubeclientError) ShouldRetry() bool {
	switch kerrors.ReasonForError(e.err) {
	case metav1.StatusReasonBadRequest,
		metav1.StatusReasonForbidden,
		metav1.StatusReasonNotFound,
		metav1.StatusReasonMethodNotAllowed,
		metav1.StatusReasonGone,
		metav1.StatusReasonInvalid:
		return false

	case metav1.StatusReasonUnauthorized,
		metav1.StatusReasonConflict,
		metav1.StatusReasonTooManyRequests,
		metav1.StatusReasonInternalError,
		metav1.StatusReasonServiceUnavailable,
		metav1.StatusReasonServerTimeout:
		return true
	}

	glog.V(8).Infof("Cannot determine reason for error %#v, will assume it's retriable", e)
	return true
}

func (e KubeclientError) ShouldBroadcast() bool {
	return !kerrors.IsConflict(e.err)
}

func (e KubeclientError) WithKind(gvk schema.GroupVersionKind) KubeclientError {
	e.gvk = gvk
	return e
}

func (e KubeclientError) WithShipperKind(kind string) KubeclientError {
	return e.WithKind(shipper.SchemeGroupVersion.WithKind(kind))
}

func (e KubeclientError) WithCoreV1Kind(kind string) KubeclientError {
	return e.WithKind(corev1.SchemeGroupVersion.WithKind(kind))
}

type kubeobj interface {
	GetName() string
	GetNamespace() string
	GroupVersionKind() schema.GroupVersionKind
}

func NewKubeclientErrorFromObject(verb KubeclientVerb, obj kubeobj, err error) KubeclientError {
	return NewKubeclientError(verb, obj.GetNamespace(), obj.GetName(), err)
}

func NewKubeclientError(verb KubeclientVerb, ns, name string, err error) KubeclientError {
	return KubeclientError{
		verb: verb,
		ns:   ns,
		name: name,
		err:  err,
	}
}

func NewKubeclientGetError(ns, name string, err error) KubeclientError {
	return NewKubeclientError(KubeclientVerbGet, ns, name, err)
}

func NewKubeclientDeleteError(ns, name string, err error) KubeclientError {
	return NewKubeclientError(KubeclientVerbDelete, ns, name, err)
}

func NewKubeclientPatchError(ns, name string, err error) KubeclientError {
	return NewKubeclientError(KubeclientVerbPatch, ns, name, err)
}

func NewKubeclientUpdateError(obj kubeobj, err error) KubeclientError {
	return NewKubeclientErrorFromObject(KubeclientVerbUpdate, obj, err)
}

func NewKubeclientCreateError(obj kubeobj, err error) KubeclientError {
	return NewKubeclientErrorFromObject(KubeclientVerbCreate, obj, err)
}

type KubeclientListError struct {
	// embed KubeclientError so we don't need a copy of ShouldRetry
	KubeclientError
	selector labels.Selector
}

func (e KubeclientListError) Error() string {
	return fmt.Sprintf("failed to list %s in namespace %q using selector %q: %s",
		e.gvk.Kind, e.ns, e.selector.String(), e.err.Error())
}

func NewKubeclientListError(gvk schema.GroupVersionKind, ns string, selector labels.Selector, err error) error {
	return KubeclientListError{
		KubeclientError: KubeclientError{
			verb: KubeclientVerbList,
			gvk:  gvk,
			ns:   ns,
			err:  err,
		},
		selector: selector,
	}
}

type KubeclientDiscoverError struct {
	// embed KubeclientError so we don't need a copy of ShouldRetry
	KubeclientError
	gv schema.GroupVersion
}

func (e KubeclientDiscoverError) Error() string {
	return fmt.Sprintf("failed to discover server resources for GroupVersion %q: %s",
		e.gv.String(), e.err.Error())
}

func NewKubeclientDiscoverError(gv schema.GroupVersion, err error) error {
	return KubeclientDiscoverError{
		KubeclientError: KubeclientError{
			verb: KubeclientVerbDiscover,
			err:  err,
		},
		gv: gv,
	}
}

func IsKubeclientError(err error) bool {
	switch err.(type) {
	case KubeclientError, KubeclientListError, KubeclientDiscoverError:
		return true
	}

	return false
}
