// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ApplicationListerExpansion allows custom methods to be added to
// ApplicationLister.
type ApplicationListerExpansion interface{}

// ApplicationNamespaceListerExpansion allows custom methods to be added to
// ApplicationNamespaceLister.
type ApplicationNamespaceListerExpansion interface{}

// CapacityTargetListerExpansion allows custom methods to be added to
// CapacityTargetLister.
type CapacityTargetListerExpansion interface{}

// CapacityTargetNamespaceListerExpansion allows custom methods to be added to
// CapacityTargetNamespaceLister.
type CapacityTargetNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// InstallationTargetListerExpansion allows custom methods to be added to
// InstallationTargetLister.
type InstallationTargetListerExpansion interface{}

// InstallationTargetNamespaceListerExpansion allows custom methods to be added to
// InstallationTargetNamespaceLister.
type InstallationTargetNamespaceListerExpansion interface{}

// RolloutBlockListerExpansion allows custom methods to be added to
// RolloutBlockLister.
type RolloutBlockListerExpansion interface{}

// RolloutBlockNamespaceListerExpansion allows custom methods to be added to
// RolloutBlockNamespaceLister.
type RolloutBlockNamespaceListerExpansion interface{}

// TrafficTargetListerExpansion allows custom methods to be added to
// TrafficTargetLister.
type TrafficTargetListerExpansion interface{}

// TrafficTargetNamespaceListerExpansion allows custom methods to be added to
// TrafficTargetNamespaceLister.
type TrafficTargetNamespaceListerExpansion interface{}
