apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm
spec:
  selector:
    matchLabels:
      app: helm
  replicas: 1
  template:
    metadata:
      labels:
        app: helm
    spec:
      containers:
        - name: app
          image: <HELM_IMAGE>
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

