// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/bookingcom/shipper/pkg/apis/shipper/v1alpha1"
	scheme "github.com/bookingcom/shipper/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CapacityTargetsGetter has a method to return a CapacityTargetInterface.
// A group's client should implement this interface.
type CapacityTargetsGetter interface {
	CapacityTargets(namespace string) CapacityTargetInterface
}

// CapacityTargetInterface has methods to work with CapacityTarget resources.
type CapacityTargetInterface interface {
	Create(*v1alpha1.CapacityTarget) (*v1alpha1.CapacityTarget, error)
	Update(*v1alpha1.CapacityTarget) (*v1alpha1.CapacityTarget, error)
	UpdateStatus(*v1alpha1.CapacityTarget) (*v1alpha1.CapacityTarget, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CapacityTarget, error)
	List(opts v1.ListOptions) (*v1alpha1.CapacityTargetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CapacityTarget, err error)
	CapacityTargetExpansion
}

// capacityTargets implements CapacityTargetInterface
type capacityTargets struct {
	client rest.Interface
	ns     string
}

// newCapacityTargets returns a CapacityTargets
func newCapacityTargets(c *ShipperV1alpha1Client, namespace string) *capacityTargets {
	return &capacityTargets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the capacityTarget, and returns the corresponding capacityTarget object, and an error if there is any.
func (c *capacityTargets) Get(name string, options v1.GetOptions) (result *v1alpha1.CapacityTarget, err error) {
	result = &v1alpha1.CapacityTarget{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("capacitytargets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CapacityTargets that match those selectors.
func (c *capacityTargets) List(opts v1.ListOptions) (result *v1alpha1.CapacityTargetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CapacityTargetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("capacitytargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested capacityTargets.
func (c *capacityTargets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("capacitytargets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a capacityTarget and creates it.  Returns the server's representation of the capacityTarget, and an error, if there is any.
func (c *capacityTargets) Create(capacityTarget *v1alpha1.CapacityTarget) (result *v1alpha1.CapacityTarget, err error) {
	result = &v1alpha1.CapacityTarget{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("capacitytargets").
		Body(capacityTarget).
		Do().
		Into(result)
	return
}

// Update takes the representation of a capacityTarget and updates it. Returns the server's representation of the capacityTarget, and an error, if there is any.
func (c *capacityTargets) Update(capacityTarget *v1alpha1.CapacityTarget) (result *v1alpha1.CapacityTarget, err error) {
	result = &v1alpha1.CapacityTarget{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("capacitytargets").
		Name(capacityTarget.Name).
		Body(capacityTarget).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *capacityTargets) UpdateStatus(capacityTarget *v1alpha1.CapacityTarget) (result *v1alpha1.CapacityTarget, err error) {
	result = &v1alpha1.CapacityTarget{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("capacitytargets").
		Name(capacityTarget.Name).
		SubResource("status").
		Body(capacityTarget).
		Do().
		Into(result)
	return
}

// Delete takes name of the capacityTarget and deletes it. Returns an error if one occurs.
func (c *capacityTargets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("capacitytargets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *capacityTargets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("capacitytargets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched capacityTarget.
func (c *capacityTargets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CapacityTarget, err error) {
	result = &v1alpha1.CapacityTarget{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("capacitytargets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
