// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ApplicationExpansion interface{}

type CapacityTargetExpansion interface{}

type ClusterExpansion interface{}

type InstallationTargetExpansion interface{}

type ReleaseExpansion interface{}

type RolloutBlockExpansion interface{}

type TrafficTargetExpansion interface{}
