// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/bookingcom/shipper/pkg/apis/shipper/v1alpha1"
	scheme "github.com/bookingcom/shipper/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RolloutBlocksGetter has a method to return a RolloutBlockInterface.
// A group's client should implement this interface.
type RolloutBlocksGetter interface {
	RolloutBlocks(namespace string) RolloutBlockInterface
}

// RolloutBlockInterface has methods to work with RolloutBlock resources.
type RolloutBlockInterface interface {
	Create(ctx context.Context, rolloutBlock *v1alpha1.RolloutBlock, opts v1.CreateOptions) (*v1alpha1.RolloutBlock, error)
	Update(ctx context.Context, rolloutBlock *v1alpha1.RolloutBlock, opts v1.UpdateOptions) (*v1alpha1.RolloutBlock, error)
	UpdateStatus(ctx context.Context, rolloutBlock *v1alpha1.RolloutBlock, opts v1.UpdateOptions) (*v1alpha1.RolloutBlock, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RolloutBlock, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RolloutBlockList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RolloutBlock, err error)
	RolloutBlockExpansion
}

// rolloutBlocks implements RolloutBlockInterface
type rolloutBlocks struct {
	client rest.Interface
	ns     string
}

// newRolloutBlocks returns a RolloutBlocks
func newRolloutBlocks(c *ShipperV1alpha1Client, namespace string) *rolloutBlocks {
	return &rolloutBlocks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rolloutBlock, and returns the corresponding rolloutBlock object, and an error if there is any.
func (c *rolloutBlocks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RolloutBlock, err error) {
	result = &v1alpha1.RolloutBlock{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rolloutblocks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RolloutBlocks that match those selectors.
func (c *rolloutBlocks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RolloutBlockList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RolloutBlockList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rolloutblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rolloutBlocks.
func (c *rolloutBlocks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rolloutblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rolloutBlock and creates it.  Returns the server's representation of the rolloutBlock, and an error, if there is any.
func (c *rolloutBlocks) Create(ctx context.Context, rolloutBlock *v1alpha1.RolloutBlock, opts v1.CreateOptions) (result *v1alpha1.RolloutBlock, err error) {
	result = &v1alpha1.RolloutBlock{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rolloutblocks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rolloutBlock).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rolloutBlock and updates it. Returns the server's representation of the rolloutBlock, and an error, if there is any.
func (c *rolloutBlocks) Update(ctx context.Context, rolloutBlock *v1alpha1.RolloutBlock, opts v1.UpdateOptions) (result *v1alpha1.RolloutBlock, err error) {
	result = &v1alpha1.RolloutBlock{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rolloutblocks").
		Name(rolloutBlock.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rolloutBlock).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rolloutBlocks) UpdateStatus(ctx context.Context, rolloutBlock *v1alpha1.RolloutBlock, opts v1.UpdateOptions) (result *v1alpha1.RolloutBlock, err error) {
	result = &v1alpha1.RolloutBlock{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rolloutblocks").
		Name(rolloutBlock.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rolloutBlock).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rolloutBlock and deletes it. Returns an error if one occurs.
func (c *rolloutBlocks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rolloutblocks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rolloutBlocks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rolloutblocks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rolloutBlock.
func (c *rolloutBlocks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RolloutBlock, err error) {
	result = &v1alpha1.RolloutBlock{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rolloutblocks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
