// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bookingcom/shipper/pkg/apis/shipper/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReleases implements ReleaseInterface
type FakeReleases struct {
	Fake *FakeShipperV1alpha1
	ns   string
}

var releasesResource = schema.GroupVersionResource{Group: "shipper.booking.com", Version: "v1alpha1", Resource: "releases"}

var releasesKind = schema.GroupVersionKind{Group: "shipper.booking.com", Version: "v1alpha1", Kind: "Release"}

// Get takes name of the release, and returns the corresponding release object, and an error if there is any.
func (c *FakeReleases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Release, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(releasesResource, c.ns, name), &v1alpha1.Release{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Release), err
}

// List takes label and field selectors, and returns the list of Releases that match those selectors.
func (c *FakeReleases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReleaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(releasesResource, releasesKind, c.ns, opts), &v1alpha1.ReleaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReleaseList{ListMeta: obj.(*v1alpha1.ReleaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReleaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested releases.
func (c *FakeReleases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(releasesResource, c.ns, opts))

}

// Create takes the representation of a release and creates it.  Returns the server's representation of the release, and an error, if there is any.
func (c *FakeReleases) Create(ctx context.Context, release *v1alpha1.Release, opts v1.CreateOptions) (result *v1alpha1.Release, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(releasesResource, c.ns, release), &v1alpha1.Release{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Release), err
}

// Update takes the representation of a release and updates it. Returns the server's representation of the release, and an error, if there is any.
func (c *FakeReleases) Update(ctx context.Context, release *v1alpha1.Release, opts v1.UpdateOptions) (result *v1alpha1.Release, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(releasesResource, c.ns, release), &v1alpha1.Release{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Release), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReleases) UpdateStatus(ctx context.Context, release *v1alpha1.Release, opts v1.UpdateOptions) (*v1alpha1.Release, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(releasesResource, "status", c.ns, release), &v1alpha1.Release{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Release), err
}

// Delete takes name of the release and deletes it. Returns an error if one occurs.
func (c *FakeReleases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(releasesResource, c.ns, name), &v1alpha1.Release{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReleases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(releasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReleaseList{})
	return err
}

// Patch applies the patch and returns the patched release.
func (c *FakeReleases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Release, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(releasesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Release{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Release), err
}
